Railway.WebUI/Controllers/RouteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Ninject;
using Railway.Services.Dto;
using Railway.Services.Interfaces;

namespace Railway.WebUI.Controllers
{
    public class RouteController : Controller
    {
        [Inject]
        public IRouteService RouteService { private get; set; } 

        [Inject]
        public ITrainStopService TrainStopService { private get; set; }

        [HttpGet]
        public ViewResult Routes()
        {
            IEnumerable<RouteDto> routes = RouteService.GetRoutes();

            return View(routes.ToList());
        }

        [HttpGet]
        public PartialViewResult StopsForRoute(int id)
        {
            IDictionary<string, TimeSpan> stops = TrainStopService.GetStopsForRoute(id);

            return PartialView(stops as Dictionary<string, TimeSpan>);
        }
    }
}

Railway.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @RenderSection("styles", required: false)

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Железная дорога", "Routes", "Route", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Маршруты", "Routes", "Route")</li>
                    <li>@Html.ActionLink("Корзина", "Basket", "Basket")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryunobtrusiveajax")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>